//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrandHotelAPP.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReservationRoom()
        {
            this.ReservationCheckOuts = new HashSet<ReservationCheckOut>();
            this.ReservationRequestTimes = new HashSet<ReservationRequestTime>();
        }
    
        public int ReservationRoomId { get; set; }
        public int ReversationId { get; set; }
        public int RoomId { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public int DurationNights { get; set; }
        public int RoomPrice { get; set; }
        public System.DateTime CheckInDateTime { get; set; }
        public System.DateTime CheckOutDateTime { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationCheckOut> ReservationCheckOuts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationRequestTime> ReservationRequestTimes { get; set; }
        public virtual Room Room { get; set; }
    }
}
