//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrandHotelAPP.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationCheckOut
    {
        public int ReservationCheckOutId { get; set; }
        public int ReservationRoomId { get; set; }
        public int ItemStatusId { get; set; }
        public int Qty { get; set; }
        public int TotalCharge { get; set; }
        public int ItemId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ItemStatu ItemStatu { get; set; }
        public virtual ReservationRoom ReservationRoom { get; set; }
    }
}
